### ISSUE TITLE
android10 SDK 29 

### ISSUE THREAD

**Issue by 0wanglei0** [shlllshlll/USBCamera#3]
08-18 15:39:19.256 31927 32020 E AndroidRuntime: Exception：调用nativeConnect返回值：-1
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:217)
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at com.shlll.libusbcamera.USBCameraHelper$2$1.run(USBCameraHelper.java:242)
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:888)
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:213)
08-18 15:39:19.256 31927 32020 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
08-18 15:39:22.517 32299 32330 E AndroidRuntime: FATAL EXCEPTION: USBCameraHelper
08-18 15:39:22.517 32299 32330 E AndroidRuntime: Process: com.shlll.usbcamera, PID: 32299
08-18 15:39:22.517 32299 32330 E AndroidRuntime: java.lang.UnsupportedOperationException: open failed:result=-1----->id_camera=494819558400;venderId=2760;productId=13101;fileDescriptor=100;busNum=2;devAddr=2;usbfs=/dev/bus/usb

**Comment by 0wanglei0** [comment]
蒲公英下载版本没有问题

**Comment by 0wanglei0** [comment]
自己手动打包出错

**Comment by 0wanglei0** [comment]
我下载了saki4510t UVCCamera的代码，但是Android10的手机无法弹出权限对话框，请问这个您是怎么解决的
